name: WebUI build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup node 🔧
        uses: actions/setup-node@master
      - name: Install, build and test 🔧
        run: |
          npm install
          npm run build
          npm test
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.COVERSALL_REPO_TOKEN }}
          BRANCH: builds
          FOLDER: dist
          CLEAN: true
